{
 "title": "Hue",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "hue_sensor_value{type=\"ZLLTemperature\"} / 100",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "hue_sensor_value{type=\"Daylight\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "hue_group_on{type=\"Room\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Battery levels",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "expr": "min(hue_sensor_battery{type=~\"(ZLLPresence|ZLLSwitch)\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Light level",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Lux" }
   ],
   "targets": [
    {
     "expr": "hue_sensor_value{type=\"ZLLLightLevel\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "hue_sensor_value{type=\"Daylight\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum(hue_group_on{type=\"Room\", name=~\"Séjour|Cuisine\"})/4",
     "legendFormat": "Eclairage Séjour/Cuisine"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "targets": [
    { "expr": "hue_light_on{}", "legendFormat": "{{ name }}" }
   ]
  }
 ]
}